### ISSUE TITLE
Shinigami92 wants to say hi :wave:

### ISSUE THREAD

**Issue by Shinigami92** [eslint-stylistic/.github#1]
I'm not only the author of `@prettier/plugin-pug`, a core member of `Vite` as well as a core maintainer of `Faker`, but I also contributed already with https://github.com/Shinigami92/eslint-define-config to the eslint ecosystem as well as a collection of other projects:

- https://github.com/typescript-eslint/typescript-eslint/issues?q=author%3AShinigami92+
- https://github.com/gajus/eslint-plugin-jsdoc/issues?q=author%3AShinigami92+
- https://github.com/vuejs/eslint-plugin-vue/issues?q=author%3AShinigami92+
- https://github.com/vuejs/vue-eslint-parser/issues?q=author%3AShinigami92+
- https://github.com/veritem/eslint-plugin-vitest/issues?q=author%3AShinigami92+
- https://github.com/muenzpraeger/eslint-plugin-inclusive-language/issues?q=author%3AShinigami92+

That's why I want to raise my hand and offer help, as long as it fits into my time frame and I gain fun out of contributing to the community

**Comment by antfu** [comment]
Sure, welcome, Shini :)
