### ISSUE TITLE
Interested in being a tester

### ISSUE THREAD

**Issue by jacob-8** [eslint-stylistic/.github#2]
@antfu - I enjoyed your prolific use of ESLint when working on UnoCSS and now I too use it solely. At first I tried adopting your default config but there's a ton of Vue stuff in there that's irrelevant for Svelte and all the Svelte rules are obviously not in there so I started from scratch. I'm still pretty fresh in this arena but I use the new flat config (eslint.config.js) and ideas from you. I love it, and would be willing to be a tester in the Svelte context for whatever comes of this package as I'm sure it will be helpful.

**Comment by antfu** [comment]
Hey Jacob. Glad to hear that!

Actually FYI, my eslint-config contains a non-vue version https://github.com/antfu/eslint-config/tree/main/packages/eslint-config-ts, which might be easier to extend with Svelte rules

**Comment by jacob-8** [comment]
> Hey Jacob. Glad to hear that!
> 
> Actually FYI, my eslint-config contains a non-vue version https://github.com/antfu/eslint-config/tree/main/packages/eslint-config-ts, which might be easier to extend with Svelte rules

Yeah, saw that too, but it was just too much of a seismic shift to drop so many rules into an already large repo. Plus, I need to learn the stuff myself so I used yours to learn from and added in one rule at a time. Thanks for the great starting point.
